version: '3.7'

services:

    server:
        container_name: server
        build:
            context: server
            dockerfile: Dockerfile
        ports:
            - 4000:4000

    client:
        container_name: client
        build:
            context: client
            dockerfile: Dockerfile
        volumes:
            - '.:/client'
            - '/client/node_modules'
        ports:
            - 3000:3000
        depends_on: 
            - server

    db:
        container_name: db
        image: postgres:alpine
        volumes:
            - ./db/create.sql:/docker-entrypoint-initdb.d/create.sql
        restart: always
        environment: 
            POSTGRES_PASSWORD: test

    adminer:
        container_name: adminer
        image: adminer
        restart: always
        ports:
            - 8080:8080